= Domain modeling in Scala

== Domain-Driven Design

[%step]
* models (data)
 ** values
 ** entities
 ** events
* behaviors
 ** factories
 ** repositories
 ** services

== Models

=== Value

> An immutable object which is only distinguishable by its properties.

[NOTE.speaker]
--
Let's start with an example using build-in types.
--

=== !

[source, scala]
--
val age:  Int    = 18
val name: String = "John Smith"
val cash: Double = 14.56
--

[source, scala]
--
age == age // true
age == (age + 1) // false

name == "John Smith" // true
name == "John Doe" // false

cash == 14.56 // true
cash == 14.57 // false
--

[NOTE.speaker]
--
Values are immutable and they are their identity - any change creates a different value.

The properties are reserves when we start aggregating smaller values into bigger values.
--

=== !

[source, scala]
--
val accountDetails: (Int, String, Double) = (age, name, cash)

accountDetails == accountDetails // true
accountDetails == accountDetails.copy(_1 = 19) // false
--

[NOTE.speaker]
--
This must be true even if we start building on top of them.

(Int, String, Double) is not really descriptive.
--

=== !

[source, scala]
--
type Age = Int
type Name = String
type Cash = Double
--

[source, scala]
--
val age:  Age  = 18
val name: Name = "John Smith"
val cash: Cash = 14.56
--

[NOTE.speaker]
--
Domain-wise built-in types are not descriptive so it's better to encode some information in type.
--

=== !

[source, scala]
--
case class AccountDetails(name: Name, age: Age, cash: Cash)
--

[source, scala]
--
val details = AccountDetails("John Smith", 18, 14.56)

details == details // true
details == details.copy(age = 19) // false
--

[NOTE.speaker]
--
As you can see nothing require us to ensure that name, age, cash is correct.
--

=== !

[source, scala]
--
type Name    = String
type Surname = String

val name:    Name    = "John"
val surname: Surname = name // :(
--

[NOTE.speaker]
--
We can solve this problem by making them separate types.
--

=== !

[source, scala]
--
case class Name(value: String) extends AnyVal
case class Surname(value: String) extends AnyVal

val name:    Name    = Name("John")
val surname: Surname = name // compiler error :)
--

[NOTE.speaker]
--
Now if we mistake 2 values we will get a compile-time error.
--

=== !

[source, scala]
--
case class Email(value: String) extends AnyVal

sealed trait EmailStatus
object EmailStatus {

  case class Confirming(unconfirmed: Email)
      extends EmailStatus

  case class Confirmed(confirmed: Email)
      extends EmailStatus

  case class Changing(old: Email, newUnconfirmed: Email)
      extends EmailStatus
}
--

=== !

[source, scala]
--
val emailStatus: EmailStatus = ...

emailStatus match {
  case EmailStatus.Confirming(unconfirmed) =>
    println(s"Email $unconfirmed is not confirmed yet")
  case EmailStatus.Confirmed(confirmed) =>
    println(s"Email is confirmed $confirmed")
  case EmailStatus.Changing(old, newUnconfirmed) =>
    println(
      s"Old email $old is confirmed" +
        s" but user requested change $newUnconfirmed"
    )
}
--

=== Entity

> An object which has some intrinsic identity, which allows tracing its state's changes in time.

=== !

[source, scala]
--
case class UserId(value: UUID) extends AnyVal
case class Name(value: String) extends AnyVal
case class Surname(value: String) extends AnyVal
case class UserData(name: Name, surname: Surname)

case class User(id: UserId, data: UserData) {

  override def equals(obj: Any): Boolean = obj match {
    case User(otherId, _) => id == otherId
    case _                => false
  }

  override def hashCode: Int = id.hashcode
}
--

=== !

[source, scala]
--
val userId = UserId(UUID.randomUUID)
val data = UserData(Name("John"), Surname("Smith"))
val user = User(userId, data)

user == user // true

import com.softwaremill.quicklens._
user == user.modify(_.data.name).set(Name("Jane")) // true

user == user.copy(id = UserId(UUID.randomUUID)) // false
--

=== Event

> An information that something happened in the system.

[NOTE.speaker]
--
It might be a call, callback, record in ledger (esp in event-sourcing).
[source, scala]
----
import $ivy.`com.softwaremill.quicklens::quicklens:1.6.0`, com.softwaremill.quicklens._
----
--

=== !

[source, scala]
--
case class UserCreationRequested(
  data: UserData
)

case class UserCreated(
  userId: UserId,
  data: UserData,
  at: Instant
)
--

[source, scala]
--
val createUser: UserCreationRequested => UserCreated
--

[NOTE.speaker]
--
How could we model events to separate business process from side effects.
--

== Behaviors

=== Side-effect free

=== !

[source, scala]
--
sealed abstract case class PlanName(value: String) {
  def +(another: PlanName): PlanName =
    new PlanName(value + " " + another.value) {}
}
object PlanName {
  def parse(value: String): Either[String, PlanName] =
    if (value.trim.isEmpty) {
      Left(s"'$value' is not a valid plan name")
    } else Right(new PlanName(value.trim) {})
}
--

[source, scala]
--
import cats.implicits._
val names: Either[String, (PlanName, PlanName)] =
  (PlanName.parse("personal"), PlanName.parse("liability"))
    .tupled
names match {
  case Right((name1, name2)) =>
    println(s"validation succeeded: ${plan1 + plan2}")
  case Left(error) =>
    println(error)
}
// validation succeeded: personal liability
--

[NOTE.speaker]
--
Smart constructors might be treated as a special case of a factory.

First use case for Cats.

[source, scala]
----
import $ivy.`org.typelevel::cats-core:2.1.0`, cats._, cats.data._, cats.implicits._
----
--

=== !

[source, scala]
--
val version2: PlanName = PlanName.parse("version 2").right.get
--

[source, scala]
--
PlanName.parse("household").flatMap { name1 =>
  PlanName.parse(name1.value + " insurance").map { name2 =>
    name2 + version2
  }
}
// Right(PlanName("household insurance version 2"))
--

[source, scala]
--
for {
  name1 <- PlanName.parse("household")
  name2 <- PlanName.parse(name1.value + " insurance")
} yield name2 + version2
--

[NOTE.speaker]
--
Show some examples in REPL here.
--

=== Side effects

=== !

[source, scala]
--
import cats.effect._

val program = IO.delay(scala.io.StdIn.readLine) // IO[String]
  .map(PlanName.parse) // IO[Either[String, PlanName]]
  .flatMap {
    case Left(error) => IO.raiseError(new Exception(error))
    case Right(name) => IO.pure(name)
  } // IO[PlanName]
  .map { name =>
    println(s"Valid plan name: $name")
  } // IO[Unit]
  .handleError {
    case e: Throwable => e.printStackTrace()
  } // IO[Unit]
--

[source, scala]
--
program.unsafeRunSync // Unit
--

[source, scala]
--
program.unsafeRunAsync { result =>
  println(s"Program finished with: $result")
} // Unit
--

[source, scala]
--
program.unsafeToFuture // Future[Unit]
--

[NOTE.speaker]
--
[source, scala]
----
import $ivy.`org.typelevel::cats-effect:2.1.3`, cats.effect._
----
--

=== !

[source, scala]
--
import scala.concurrent.duration._

IO.delay(scala.io.StdIn.readLine)
  .flatMap { in =>
     val nap      = IO.sleep(2.second)
     val asBool   = nap >> IO.delay(in.toBoolean).attempt
     val asInt    = nap >> IO.delay(in.toInt).attempt
     val asDouble = nap >> IO.delay(in.toDouble).attempt
     (asBool, asInt, asDouble).parMapN { (b, i, d) =>
       println(s"$in:\nbool: $b,\nint: $i,\ndouble: $d")
     }
  }
  .unsafeRunAsync(result => println(result))
--

[NOTE.speaker]
--
Requires previous definitions and:
[source, scala]
----
implicit val contextShift: cats.effect.ContextShift[IO] = IO.contextShift(
  scala.concurrent.ExecutionContext.global
)

implicit val timer: cats.effect.Timer[IO] = IO.timer(
  scala.concurrent.ExecutionContext.fromExecutorService(
    java.util.concurrent.Executors.newCachedThreadPool()
  )
)
----
--

== Services

=== Plan's subdomain

=== !

[source, scala]
--
case class PlanId(value: UUID) extends AnyVal
case class PlanVersion(value: Int) extends AnyVal
case class PlanVersionedId(id: PlanId, version: PlanVersion)

sealed trait PlanStatus
object PlanStatus {
  case object NotLaunched extends PlanStatus
  case class Launched(at: Instant) extends PlanStatus
  case class Retired(validFrom: Instant, validUntil: Instant)
    extends PlanStatus
}

case class PlanData(name: PlanName, status: PlanStatus)
--

[source, scala]
--
case class Plan(versionedId: PlanVersionedId, data: PlanData){
  override def equals(obj: Any): Boolean = obj match {
    case Plan(`versionedId`, _) => true
    case _                      => false
  }
  override def hashCode: Int = versionedId.hashCode
}
--

[NOTE.speaker]
--
[source, scala]
----
import java.util.UUID
import java.time.Instant
----
--

=== !

[source, scala]
--
trait PlanServices {

  def createPlan(data: PlanData): IO[Plan]
  def updatePlan(id: PlanId, data: PlanData): IO[Plan]
  def launchPlan(versionedId: PlanVersionedId,
                 at: Instant): IO[Plan]
  def retirePlan(versionedId: PlanVersionedId,
                 at: Instant): IO[Plan]
}
--

[source, scala]
--
trait PlanRepository {

  def listActivePlans: IO[List[Plan]]
  def listPlanVersions(id: PlanId): IO[List[Plan]]
  def getExactPlan(versionedId: PlanVersionedId): IO[Plan]
  def getLastestPlan(id: PlanId): IO[Plan]
}
--

[NOTE.speaker]
--
Examples of plan services and repositories.
[source, scala]
----
import scala.collection.immutable.ListMap
import cats.effect.concurrent.Ref

val (planRepository, planServices) = {
val inMemory = Ref.unsafe[IO, Map[PlanId, ListMap[PlanVersion, Plan]]](Map.empty)

val repo: PlanRepository = new PlanRepository {
  def listActivePlans: IO[List[Plan]] = inMemory.get.map { plans =>
    val now = Instant.now
    plans.values.toList.flatMap(_.values.toList).filter { plan =>
      plan.data.status match {
        case PlanStatus.NotLaunched       => false
        case PlanStatus.Launched(at)      => at.isBefore(now)
        case PlanStatus.Retired(from, to) => from.isBefore(now) && now.isBefore(to)
      }
    }
  }
  def listPlanVersions(id: PlanId): IO[List[Plan]] = inMemory.get.map(_(id).values.toList)
  def getExactPlan(versionedId: PlanVersionedId): IO[Plan] = inMemory.get.map(_(versionedId.id)(versionedId.version))
  def getLastestPlan(id: PlanId): IO[Plan] = inMemory.get.map(_(id).last._2)
}

val services: PlanServices = new PlanServices {
  def createPlan(data: PlanData): IO[Plan] = {
    val id = PlanId(java.util.UUID.randomUUID)
    val version = PlanVersion(1)
    val plan = Plan(PlanVersionedId(id, version), data)
    inMemory.update { plans =>
      plans.updated(id, ListMap(version -> plan))
    } >> IO.pure(plan)
  }
  def updatePlan(id: PlanId, data: PlanData): IO[Plan] = inMemory.updateAndGet { plans =>
    val newPlan = plans(id).last._2
      .modify(_.versionedId.version).using(old => PlanVersion(old.value + 1))
      .modify(_.data).setTo(data)
    plans.updatedWith(newPlan.versionedId.id)(_.map(_ + (newPlan.versionedId.version -> newPlan)))
  }.map(_(id).last._2)
  def launchPlan(versionedId: PlanVersionedId,
                 at: Instant): IO[Plan] = inMemory.updateAndGet {
    _.modify(_.at(versionedId.id).at(versionedId.version).data.status).setTo(PlanStatus.Launched(at))
  }.map(_(versionedId.id)(versionedId.version))
  def retirePlan(versionedId: PlanVersionedId,
                 at: Instant): IO[Plan] = inMemory.updateAndGet {
    _.modify(_.at(versionedId.id).at(versionedId.version).data.status).using {
      case PlanStatus.Launched(from) => PlanStatus.Retired(from, at)
      case _                         => PlanStatus.Retired(at, at)
    }
  }.map(_(versionedId.id)(versionedId.version))
}

repo -> services
}
----
--

=== !

[source, scala]
--
val planName = PlanName.parse("my plan").right.get
val planLifecycleTest = for {
  plan1 <- planServices.createPlan(
      PlanData(planName, PlanStatus.NotLaunched))
  _ <- planServices.launchPlan(plan1.versionedId, Instant.now)
  _ <- IO.sleep(1.second)
  active <- planRepository.listActivePlans
  _ = println("Active plans\n" + active.mkString("\n"))
  retired <- planServices.retirePlan(plan1.versionedId,
                                     Instant.now)
} yield retired
--

[source, scala]
--
val planVersioningTest = for {
  oldPlan <- planLifecycleTest
  plan2 <- planServices.updatePlan(
      oldPlan.versionedId.id,
      PlanData(oldPlan.data.name, PlanStatus.NotLaunched))
  versions <- planRepository.listPlanVersions(
      plan2.versionedId.id)
  _ = println("Versions\n" + versions.mkString("\n"))
} yield versions
--

[source, scala]
--
planVersioningTest.unsafeRunSync
--

[NOTE.speaker]
--
From this moment on, no mocks as it would be too much to bother.
--

=== Contract's subdomain

=== !

[source, scala]
--
case class CustomerId(value: UUID) extends AnyVal
case class ContractId(value: UUID) extends AnyVal
sealed trait ContractDuration
object ContractDuration {
  case class Fixed(from: ZonedDate, until: Instant)
    extends ContractDuration
  case class Renewed(from: Instant, lastRenewal: Instant,
                     terminated: Option[Instant])
    extends ContractDuration
}
case class Coverage(start: Instant, end: Instant)
--

[source, scala]
--
case class ContractData(
  customerId: CustomerId,       planVersion: PlanVersionedId
  duration:   ContractDuration, coverage:    Coverage
)
--

[source, scala]
--
case class Contract(id: ContractId, data: ContractData) {
  override def equals(obj: Any): Boolean = obj match {
    case Plan(`id`, _) => true
    case _             => false
  }
  override def hashCode: Int = versionedId.hashCode
}
--

=== !

[source, scala]
--
trait ContractServices {

  def createContract(data: ContractData): IO[Contract]
  def renewContract(
        id: ContractId,
        nextRenewal: Instant,
        nextCoverageEnd: Instant): IO[List[Contract]]
  def terminateContract(id: ContractId,
                        at: Instant): IO[Contract]
}
--

[source, scala]
--
trait ContractRepository {

  def getContract(id: ContractId): IO[Contract]
  def listContractsForCustomer(
        customerId: CustomerId): IO[List[Contract]]
  def listContractsForRenewal(at: Instant): IO[List[Contract]]
}
--

=== !

[source, scala]
--
sealed trait ContractEvent
case class ContractCreated(id: ContractId)
    extends ContractEvent
case class ContractRenewed(id: ContractId)
    extends ContractEvent
case class ContractTerminated(id: ContractId)
    extends ContractEvent
--

=== Customer's subdomain

=== !

[source, scala]
--
case class CustomerData(
  name:      CustomerName,
  surname:   CustomerSurname,
  addresses: NonEmptyList[Address],
  email:     Email
)
case class Customer(id: CustomerId, data: CustomerData) {
  // ... override equals and hashCode
}
--

[source, scala]
--
trait CustomerRepository {
  def getCustomerById(id: CustomerId): IO[Customer]
}
--

=== Payment's domain

=== !

[source, scala]
--
case class PaymentId(value: UUID) extends AnyVal
sealed trait PaymentType
object PaymentType {
  case object SinglePayment extends PaymentType
  case class Subscription(renewEvery: Duration)
      extends PaymentType
}
sealed trait PaymentStatus
object PaymentStatus {
  case object Scheduled extends PaymentStatus
  case object Completed extends PaymentStatus
  case object Failed extends PaymentStatus
  case object Cancelled extends PaymentStatus
}
--

=== !

[source, scala]
--
sealed trait PaymentMethod
object PaymentMethod {
  case class CreditCard(...) extends PaymentMethod
  case class Stripe(...) extends PaymentMethod
  case class PayPal(...) extends PaymentMethod
  ...
}
--

[source, scala]
--
case class PaymentData(
  contractId:      ContractId,
  paymentType:     PaymentType,
  paymentMethod:   PaymentMethod,
  status:          PaymentStatus,
  amount:          Money,
  customerId:      CustomerId,
  customerName:    CustomerName,
  customerSurname: CustomerSurname,
  invoiceAddress:  Address
)
case class Payment(id: PaymentId, data: PaymentData) {
  // ... override equals and hashCode
}
--

=== !

[source, scala]
--
import squants.market._

trait QuotingServices {
  def quoteForContract(
        data: ContractData): IO[(Money, PaymentType)]
}
--

[source, scala]
--
trait CustomerPaymentMethodServices {
  def setMethodForCustomer(
        customerId: CustomerId,
        paymentMethod: PaymentMethod): IO[Unit]
  def getMethodForCustomer(
        customerId: CustomerId): IO[PaymentMethod]
}
--

[source, scala]
--
trait PaymentServices {
  def schedulePayment(data: PaymentData): IO[Payment]
  def renewPayment(paymentId: PaymentId,
                   at: Instant): IO[Payment]
  def retryPayment(
        paymentId: PaymentId,
        newMethod: Option[PaymentMethod]): IO[Payment]
}
--

=== Event sourcing

=== !

[source, scala]
--
def createPayment(contractId: ContractId) = for {
  contract <- contractRepository.getContract(contractId)
  customerId = contractData.customerId
  customer <- customerRepository.getCustomerById(customerId)
  method <- customerPaymentMethodServices
    .getMethodForCustomer(customerId)
  (price, paymentType) <-
    quotingServices.quoteForContract(contract.data)
  data = PaymentData(contractId, paymentType, method,
    PaymentStatus.Scheduled, price, customerId,
    customerData.name, customerData.surname,
    customerData.addresses.head)
  payment <- paymentServices.createPayment(data)
} yield payment
--

[NOTE.speaker]
--
Requires better-monadic-for.
--

=== !

[source, scala]
--
import fs2._

val contractEvents: Stream[IO, ContractEvent] = ...

val paymentsCreationProjection: IO[Unit] =
  contractEvent
    .collect {
      case ContractCreated(contractId) => contractId
    }
    .evalMap(createPayment)
    .drain.compile
--

=== !

[source, scala]
--
val fiber: IO[Fiber[IO, Unit]] =
  paymentsCreationProjection.start
--

[source, scala]
--
val projections = for {
  _ <- paymentsCreationProjection.start
  _ <- paymentsRenewedProjection.start
  _ <- paymentsCancelledProjection.start
  _ = println("All projections started")
} yield ()
--

== Other interesting things that we didn't have space for

[%step]
* resources (e.g. https://typelevel.org/cats-effect/datatypes/resource.html[`cats.effect.Resource[IO, A]`])
* persistence (e.g. https://tpolecat.github.io/doobie/[Doobie])
* serialization (e.g. https://circe.github.io/circe/[Circe])
* HTTP (e.g. https://http4s.org/[Http4s] and https://sttp.softwaremill.com/en/latest/[STTP])

=== Some E2E examples of services in Cats

That I've written:

* https://github.com/MateuszKubuszok/remote-sync-example[Deezer-Postgres synchronization service]
* https://github.com/MateuszKubuszok/branchtalk[Reddit clone]

== Summary

== Questions?
